#!/bin/bash

awk '//{
if(NR==1)
{
	system("gnome-terminal --working-directory=\""gensub(/~/,"/home/david",1,$0)"\"");
	nautilus_path = gensub(/\s|[]()&[]/,"\\\\&","g",$0);
	system("nautilus "nautilus_path" &>>/dev/null &");
}
else
{
	system($0" &>>/dev/null &");
}
}' $WKSPACE/$1 &>>/dev/null
