#!/bin/bash

# wkspace-management
# Author: David Chang
# Last revision: Mar 26th, 2019

# get current desktop
desk=$(wmctrl -d |awk '//{if($2=="*") num = $1;} END{print num;}')

# get PIDs and stores
wmctrl -l -p -x |awk -v desk=$desk '// {
if($2==desk)
{
	if($4=="gnome-terminal-server.Gnome-terminal")
		path = substr($0,index($0,":")+2);
	else if($4!="nautilus.Nautilus"&&$4!="Navigator.Firefox"&&$4!="desktop_window.Nautilus")
		pid[NR] = $3;
}
}
END {
print path;
for(n in pid)
	print pid[n];
}' |awk 'BEGIN {
"date \"+%Y-%m-%d\"" |getline date;
close("date \"+%Y-%m-%d\"");
}
// {
if(NR==1)
{
	#split($0,pathItem,"/");
	#path = pathItem[length(pathItem)];
	path = gensub("/",".","g",$0);
	path = gensub(/\s/,"+","g",path);
	print $0 >"'$WKSPACE'/"date"-"path;
}
else
{
	command = "ps -eo \"%p %a\" |grep "$0;
	for(;(command |getline exec)==1;)
	{
		split(exec,execItems)
		if(execItems[1]==$0)
		{
			targetCommand = substr(exec,index(exec,execItems[2]));
			print targetCommand >>"'$WKSPACE'/"date"-"path;
			close(command);
			break;
		}
	}
}
}'

# check the dumped workspace
wkspcs=($(ls -t $WKSPACE))
chk-wkspace ${wkspcs[0]}
